import Head from "next/head";
import Header from "../components/header/Header";
import Instagram from "../components/Instagram/Instagram";
import KeeperPage from "../components/Keeper/KeeperPage";
import Stack from "../components/Stacks/Stack";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Burak Kaplan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=McLaren&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Courier+Prime&family=McLaren&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Header />
      <KeeperPage />
      <Instagram />
      <Stack />
    </div>
  );
}
